name: Xchant
version: '1.1.0'
main: ooo.paulsen.mc.xchant.Xchant
api-version: 1.19
softdepend: [ EPvP ]
authors: [ Paulsenik ]
description: Enchant items with extended limits
website: https://paulsenik.de/

commands:
  xchant:
    description: Open Settings for "Xchant"
    usage: /<command> opens settings
    permission: op
  howto-xchant:
    description: Open Manual for "Xchant"
    usage: /<command> opens how-to-book